ServerName localhost

<VirtualHost *:8080>
    DocumentRoot /my-app/rbs

    <Directory /my-app/rbs>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    ErrorLog /dev/stderr
    CustomLog /dev/stdout combined
</VirtualHost>
